backbone:
  # [from, module, args]
  - [-1, StemBlock, [16, 16, True]] # 0-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']] # 1-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']] # 2-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]  # 3-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']] # 4-P5/32

encoder:
  - [1, ConvNormLayer_fuse, [256, 1, 1]] # 5-P2/4
  - [2, ConvNormLayer_fuse, [256, 1, 1]] # 6-P3/8
  - [3, ConvNormLayer_fuse, [256, 1, 1]] # 7-P4/16
  - [4, ConvNormLayer_fuse, [256, 1, 1]] # 8-P5/32

  - [-1, TransformerEncoderBlock, [8, 1024, 0.1, "relu", 10000, False]] # 9-P5/32

  - [-1, ConvNormLayer_fuse, [256, 1, 1]]
  - [-1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 7], Concat, []] # 12-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 13-P4/16

  - [-1, ConvNormLayer_fuse, [256, 1, 1]]
  - [-1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], Concat, []] # 16-P3/8
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 17-P3/8

  - [-1, ConvNormLayer_fuse, [256, 1, 1]]
  - [-1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 5], Concat, []] # 20-P2/4
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 21-P2/4

  - [-1, SCDown, [256, 3, 2, 'silu']] # 22-P3/8
  - [[-1, 18], Concat, []] # 23-P3/8
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 24-P3/8

  - [-1, SCDown, [256, 3, 2, 'silu']] # 25-P4/16
  - [[-1, 14], Concat, []] # 26-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 27-P4/16

  - [-1, SCDown, [256, 3, 2, 'silu']] # 28-P5/32
  - [[-1, 10], Concat, []] # 29-P5/32
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 30-P5/32

decoder:
  - [[21, 24, 27, 30], DFINETransformer, {"feat_strides":[4, 8, 16, 32], "hidden_dim": 256, "num_levels": 4, "num_layers": 3, "num_points": [3, 3, 6, 3], "dim_feedforward": 1024}]