backbone:
  # [from, module, args]
  - [-1, StemBlock, [16, 16, True]] # 0-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']] # 1-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']] # 2-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]  # 3-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']] # 4-P5/32

encoder:
  - [3, ConvNormLayer_fuse, [128, 1, 1]] # 5-P4/16
  - [4, ConvNormLayer_fuse, [128, 1, 1]] # 6-P5/32

  - [-1, TransformerEncoderBlock, [8, 512, 0.1, "relu", 10000, False]] # 7-P5/32

  - [[2, 5, 7], PyramidPoolAgg, [128, 2]] # 8-P6/64
  - [-1, TopBasicLayer, [[64, 128]]] # 9-P6/64

  - [[2, 5], AdvPoolFusion, []] # 10-P4/16
  - [[-1, 9], InjectionMultiSum_Auto_pool, [128, [64, 128], 0]] # 11-P4/16
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']] # 12-P4/16

  - [[-1, 7], AdvPoolFusion, []] # 13-P5/32
  - [[-1, 9], InjectionMultiSum_Auto_pool, [128, [64, 128], 1]] # 14-P5/32
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']] # 15-P5/32

decoder:
  - [[12, 15], DFINETransformer, {"feat_strides":[16, 32], "hidden_dim": 128, "num_levels": 2, "num_layers": 3, "num_points": [6, 6], "dim_feedforward": 512}]