backbone:
  # [from, module, args]
  - [-1, StemBlock, [16, 16, True]] # 0-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']] # 1-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']] # 2-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]  # 3-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']] # 4-P5/32

encoder:
  - [2, ConvNormLayer_fuse, [256, 1, 1]] # 5-P3/8
  - [3, ConvNormLayer_fuse, [256, 1, 1]] # 6-P4/16
  - [4, ConvNormLayer_fuse, [256, 1, 1]] # 7-P5/32

  - [-1, TransformerEncoderBlock, [8, 1024, 0.1, "relu", 10000, False]] # 8-P5/32

  - [-1, ConvNormLayer_fuse, [256, 1, 1]] # 9-P5/32
  - [[6, -1], MultiScalePCA, [256]] # 10-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 11-P4/16

  - [-1, ConvNormLayer_fuse, [256, 1, 1]] # 12-P4/16
  - [[5, -1], MultiScalePCA, [256]] # 13-P3/8
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 14-P3/8

  - [[12, -1], MultiScalePCA_Down, [256]] # 15-P4/16
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 16-P4/16

  - [[9, -1], MultiScalePCA_Down, [256]] # 17-P5/32
  - [-1, RepNCSPELAN4, [256, 512, 64, 1, False, 'silu']] # 18-P5/32

decoder:
  - [[14, 16, 18], DFINETransformer, {"feat_strides":[8, 16, 32], "hidden_dim": 256, "num_levels": 3, "num_layers": 3, "num_points": [3, 6, 3], "dim_feedforward": 1024}]